[platformio]
default_envs = esp32

[env:esp32]
platform = espressif32@6.9.0
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchon/ArduinoJson@^7.0.0
    knolleary/PubSubClient@^2.8
    mathieucarbou/ESPAsyncWebServer@^3.3.0
    mathieucarbou/AsyncTCP@^3.2.0
    ihormelnyk/OpenTherm Library@^1.1.5
    olikraus/U8g2@^2.35.0
lib_ldf_mode = deep+
build_flags =
    -DCORE_DEBUG_LEVEL=3
    -DUSE_WIFI=1
    -DPIN_STATUS_LED=2
    -DBOARD_TYPE=\"esp32\"
    -DPIN_OT_IN=21
    -DPIN_OT_OUT=22
    -DPIN_SDA=19
    -DPIN_SCL=23
    -DPIN_ENC_CLK=16
    -DPIN_ENC_DT=17
    -DPIN_ENC_SW=5
extra_scripts =
    pre:scripts/version.py
    scripts/gzip_webfiles.py
board_build.filesystem = littlefs
board_build.partitions = partitions_webui.csv
