// In simulate-ot builds the real driver is bypassed by `ot_master::simulate()`,
// so the public API here looks unused to the compiler. Keep the surface around
// for API symmetry without spamming warnings.
#![cfg_attr(feature = "simulate-ot", allow(dead_code))]

//! Pure-Rust OpenTherm master driver using the ESP32 RMT peripheral.
//!
//! Replaces the previous C++ component. The RMT hardware handles bit timing
//! in hardware, so neither TX nor RX requires disabling interrupts —
//! eliminating the ~34 ms blackout per request that caused WiFi/OTA lag in
//! the old driver.
//!
//! Protocol summary:
//!   * 34-bit frame: start bit (1) + 32 data bits MSB-first + stop bit (1)
//!   * Manchester-like encoding, 1 ms / bit (500 µs / half-bit)
//!   * bit 1 = wire LOW 500 µs → HIGH 500 µs
//!   * bit 0 = wire HIGH 500 µs → LOW 500 µs
//!   * Idle line = HIGH

/// 3-bit message-type field stored at frame bits 30-28.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum MessageType {
    ReadData = 0,
    WriteData = 1,
    InvalidData = 2,
    Reserved = 3,
    ReadAck = 4,
    WriteAck = 5,
    DataInvalid = 6,
    UnknownDataId = 7,
}

/// Outcome of the most recent `send_request`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ResponseStatus {
    None,
    Success,
    Invalid,
    Timeout,
}

/// Build a 34-bit OpenTherm frame:
///   [31] parity (odd over bits 30-0)
///   [30:28] message type
///   [27:24] spare (always 0)
///   [23:16] data ID
///   [15:0]  data value
fn build_frame(msg_type: MessageType, data_id: u8, data: u16) -> u32 {
    let mut frame: u32 = data as u32;
    if matches!(msg_type, MessageType::WriteData) {
        frame |= 1 << 28;
    }
    frame |= (data_id as u32) << 16;
    if odd_parity(frame) {
        frame |= 1 << 31;
    }
    frame
}

fn extract_msg_type(frame: u32) -> MessageType {
    match ((frame >> 28) & 0x07) as u8 {
        0 => MessageType::ReadData,
        1 => MessageType::WriteData,
        2 => MessageType::InvalidData,
        3 => MessageType::Reserved,
        4 => MessageType::ReadAck,
        5 => MessageType::WriteAck,
        6 => MessageType::DataInvalid,
        _ => MessageType::UnknownDataId,
    }
}

/// True if the frame contains an odd number of 1 bits. Used both for generating
/// the parity bit (set bit 31 when the rest of the frame has odd parity, so
/// the *full* 32-bit frame has even parity) and for validating responses
/// (a valid response has even parity over all 32 bits).
fn odd_parity(frame: u32) -> bool {
    frame.count_ones() & 1 == 1
}

// ---------------------------------------------------------------------------
// Simulation mode — no hardware access. Real I/O is mocked out by ot_master.
// ---------------------------------------------------------------------------

#[cfg(feature = "simulate-ot")]
pub struct OpenTherm {
    last_status: ResponseStatus,
}

#[cfg(feature = "simulate-ot")]
impl OpenTherm {
    pub fn new(_in_pin: i32, _out_pin: i32) -> Result<Self, &'static str> {
        Ok(Self { last_status: ResponseStatus::None })
    }

    pub fn send_request(&mut self, _request: u32) -> u32 {
        self.last_status = ResponseStatus::Success;
        0
    }

    pub fn last_status(&self) -> ResponseStatus {
        self.last_status
    }

    pub fn build_request(msg_type: MessageType, data_id: u8, data: u16) -> u32 {
        build_frame(msg_type, data_id, data)
    }

    pub fn get_message_type(frame: u32) -> MessageType {
        extract_msg_type(frame)
    }
}

// ---------------------------------------------------------------------------
// RMT-backed implementation.
// ---------------------------------------------------------------------------

#[cfg(not(feature = "simulate-ot"))]
mod rmt {
    use super::*;
    use core::ptr;
    use core::sync::atomic::{AtomicUsize, Ordering};
    use esp_idf_svc::hal::delay::FreeRtos;
    use esp_idf_svc::sys::{
        configTICK_RATE_HZ, esp_err_t, gpio_num_t, rmt_channel_handle_t,
        rmt_copy_encoder_config_t, rmt_del_channel, rmt_del_encoder, rmt_disable,
        rmt_enable, rmt_encoder_handle_t, rmt_new_copy_encoder, rmt_new_rx_channel,
        rmt_new_tx_channel, rmt_receive, rmt_receive_config_t,
        rmt_rx_channel_config_t, rmt_rx_done_event_data_t, rmt_rx_event_callbacks_t,
        rmt_rx_register_event_callbacks, rmt_symbol_word_t, rmt_transmit,
        rmt_transmit_config_t, rmt_tx_channel_config_t, rmt_tx_wait_all_done,
        soc_periph_rmt_clk_src_t_RMT_CLK_SRC_REF_TICK, vQueueDelete,
        xQueueCreateCountingSemaphore, xQueueGiveFromISR, xQueueReceive, BaseType_t,
        QueueHandle_t, ESP_OK,
    };

    /// FreeRTOS `pdTRUE` — `#define`d in C, so not generated by bindgen.
    const PD_TRUE: BaseType_t = 1;

    const HALF_BIT_US: u16 = 500;
    /// Pulse widths above this are interpreted as two half-bits (a bit-boundary merge).
    const MERGE_THRESHOLD_US: u16 = 750;
    /// TX is timed at 1 µs / tick so the 500 µs half-bits encode exactly. The
    /// HALF_BIT_US constant is reused directly as a tick count in encode_bit_word.
    const TX_RESOLUTION_HZ: u32 = 1_000_000;
    /// RX uses a coarser 10 µs / tick to make signal_range_max_ns large enough
    /// to span the slave's 20-800 ms response delay. At 1 MHz the 15-bit
    /// idle-threshold register caps out at ~32 ms; at 100 kHz it reaches
    /// ~327 ms. 10 µs granularity on RX is still ~50× tighter than a half-bit,
    /// well within Manchester decode tolerance.
    const RX_RESOLUTION_HZ: u32 = 100_000;
    /// 10 µs per RX tick (= 1 / RX_RESOLUTION_HZ in seconds).
    const RX_US_PER_TICK: u32 = 1_000_000 / RX_RESOLUTION_HZ;
    /// 1 start + 32 data + 1 stop.
    const FRAME_BITS: usize = 34;
    /// Generous worst-case RX buffer — only ~34 symbols are ever produced for a
    /// valid frame, but noisy bus edges can split pulses further.
    const RX_BUFFER_SYMBOLS: usize = 64;
    /// Total master-to-slave timeout including the master's own ~34 ms TX.
    const RESPONSE_TIMEOUT_MS: u32 = 1100;
    /// Recovery delay after every exchange (matches the C++ DELAY state).
    const RECOVERY_DELAY_MS: u32 = 100;

    fn ms_to_ticks(ms: u32) -> u32 {
        ms.saturating_mul(configTICK_RATE_HZ) / 1000
    }

    /// Encode one OpenTherm bit as an `rmt_symbol_word_t.val` payload.
    /// Layout (LSB→MSB): duration0:15, level0:1, duration1:15, level1:1.
    fn encode_bit_word(bit: bool) -> u32 {
        let (lvl0, lvl1) = if bit {
            (0u32, 1u32) // 1: LOW → HIGH
        } else {
            (1u32, 0u32) // 0: HIGH → LOW
        };
        let d = HALF_BIT_US as u32;
        d | (lvl0 << 15) | (d << 16) | (lvl1 << 31)
    }

    /// Encode a 34-bit frame into RMT TX symbols.
    fn encode_frame(frame: u32) -> [rmt_symbol_word_t; FRAME_BITS] {
        let mut out = [rmt_symbol_word_t { val: 0 }; FRAME_BITS];
        // Start bit
        out[0] = rmt_symbol_word_t { val: encode_bit_word(true) };
        // 32 data bits, MSB first
        for i in 0..32 {
            let bit = ((frame >> (31 - i)) & 1) == 1;
            out[1 + i] = rmt_symbol_word_t { val: encode_bit_word(bit) };
        }
        // Stop bit
        out[33] = rmt_symbol_word_t { val: encode_bit_word(true) };
        out
    }

    /// Decode the half-bit expansion of received RMT symbols back into a 32-bit
    /// frame. See design.md §4 for the algorithm proof.
    ///
    /// Two real-world details the basic Manchester model doesn't cover:
    ///
    /// * **Leading HIGH idle.** After we set `eot_level=1` and arm RX, the
    ///   bus stays HIGH until the slave starts responding 20-100 ms later.
    ///   RMT captures that idle as one or more HIGH pulses before the actual
    ///   start bit. Since the OT start bit is "1" (LOW → HIGH), any HIGH
    ///   half-bit observed before the first LOW is idle and must be skipped.
    /// * **Trailing HIGH idle.** After the slave's stop bit, the line goes
    ///   back to HIGH and RMT closes the receive window ~1.5 ms later. That
    ///   tail-end HIGH is recorded as one extra pulse we need to ignore once
    ///   we already have the 68 half-bits of the frame.
    fn decode_symbols(items: &[rmt_symbol_word_t]) -> Result<u32, ()> {
        let mut half_bits: [bool; FRAME_BITS * 2] = [false; FRAME_BITS * 2];
        let mut n = 0usize;
        let mut started = false;

        'outer: for sym in items {
            let val = unsafe { sym.val };
            if val == 0 {
                break; // zero symbol = end of capture
            }
            let d0 = (val & 0x7FFF) as u16;
            let l0 = ((val >> 15) & 0x1) != 0;
            let d1 = ((val >> 16) & 0x7FFF) as u16;
            let l1 = ((val >> 31) & 0x1) != 0;

            for &(dur, lvl) in &[(d0, l0), (d1, l1)] {
                if dur == 0 {
                    break;
                }
                // RX runs at 100 kHz (10 µs / tick); convert to µs for the
                // merge-threshold comparison.
                let dur_us = (dur as u32).saturating_mul(RX_US_PER_TICK);
                // Skip any leading HIGH idle before the slave's start bit.
                if !started {
                    if lvl {
                        continue;
                    }
                    started = true;
                }
                // We already have the full frame — anything beyond is the
                // trailing HIGH idle the RMT records before closing.
                if n >= FRAME_BITS * 2 {
                    break 'outer;
                }
                half_bits[n] = lvl;
                n += 1;
                if dur_us > MERGE_THRESHOLD_US as u32 {
                    if n >= FRAME_BITS * 2 {
                        break 'outer;
                    }
                    half_bits[n] = lvl;
                    n += 1;
                }
            }
        }

        // RMT's signal_range_max_ns close trigger is itself the pulse that
        // ends the receive — that pulse is *not* written to the buffer. For
        // OT frames the trailing pulse is the stop bit's second half (HIGH)
        // merged with the trailing idle, so we systematically lose h[67].
        // We can recover deterministically: the stop bit must be 1 (encoded
        // LOW→HIGH), so h[67] is always HIGH when the rest of the frame is
        // intact. Pad it when we ended exactly one half-bit short.
        if n == FRAME_BITS * 2 - 1 {
            half_bits[n] = true;
            n += 1;
        }
        if n != FRAME_BITS * 2 {
            return Err(());
        }

        // Reconstruct the 32 data bits (skip pair 0 = start, pair 33 = stop).
        let mut frame: u32 = 0;
        for pair in 0..FRAME_BITS {
            let first = half_bits[pair * 2];
            let second = half_bits[pair * 2 + 1];
            let bit = match (first, second) {
                (false, true) => true,  // LOW → HIGH = 1
                (true, false) => false, // HIGH → LOW = 0
                _ => return Err(()),
            };
            if pair >= 1 && pair <= 32 {
                frame = (frame << 1) | (bit as u32);
            } else if pair == 0 && !bit {
                return Err(()); // start bit must be 1
            } else if pair == 33 && !bit {
                return Err(()); // stop bit must be 1
            }
        }

        // Valid response has even parity over all 32 bits (so odd_parity == false).
        if odd_parity(frame) {
            return Err(());
        }

        Ok(frame)
    }

    /// Stable, ISR-safe context handed to the RX done callback.
    struct RxContext {
        sem: QueueHandle_t,
        received_count: AtomicUsize,
    }

    /// Fires from RMT ISR when an RX capture window closes. Records the symbol
    /// count and unblocks `send_request`.
    unsafe extern "C" fn on_rx_done(
        _chan: rmt_channel_handle_t,
        edata: *const rmt_rx_done_event_data_t,
        user_ctx: *mut core::ffi::c_void,
    ) -> bool {
        let ctx = &*(user_ctx as *const RxContext);
        let count = if !edata.is_null() { (*edata).num_symbols } else { 0 };
        ctx.received_count.store(count, Ordering::Release);

        let mut woken: BaseType_t = 0;
        xQueueGiveFromISR(ctx.sem, &mut woken as *mut BaseType_t);
        woken == PD_TRUE
    }

    /// RMT-backed OpenTherm master.
    pub struct OpenTherm {
        tx_chan: rmt_channel_handle_t,
        rx_chan: rmt_channel_handle_t,
        encoder: rmt_encoder_handle_t,
        rx_buffer: Box<[rmt_symbol_word_t; RX_BUFFER_SYMBOLS]>,
        ctx: Box<RxContext>,
        last_status: ResponseStatus,
    }

    impl OpenTherm {
        pub fn new(in_pin: i32, out_pin: i32) -> Result<Self, &'static str> {
            unsafe {
                // TX channel on `out_pin`
                let mut tx_cfg: rmt_tx_channel_config_t = core::mem::zeroed();
                tx_cfg.gpio_num = out_pin as gpio_num_t;
                // Both TX and RX must share a clock source on the ESP32 RMT
                // group; using REF_TICK (1 MHz) lets the RX channel reach a
                // low enough resolution for the long signal_range_max_ns we
                // need (see RX_RESOLUTION_HZ comment). TX still gets 1 µs /
                // tick from REF_TICK with divider 1.
                tx_cfg.clk_src = soc_periph_rmt_clk_src_t_RMT_CLK_SRC_REF_TICK;
                tx_cfg.resolution_hz = TX_RESOLUTION_HZ; // 1 µs / tick
                tx_cfg.mem_block_symbols = 64;
                tx_cfg.trans_queue_depth = 2;
                // Drive the line HIGH while no transmission is active. The
                // bindgen-generated bitfield setters are inside __bindgen_anon_*;
                // we use the union's `val: u32` view in the symbol path but the
                // config flags field is a plain struct so the setters are direct.
                // We leave flags zeroed — invert_out=0 (no inversion).

                let mut tx_chan: rmt_channel_handle_t = ptr::null_mut();
                if rmt_new_tx_channel(&tx_cfg, &mut tx_chan) != ESP_OK as esp_err_t {
                    return Err("rmt_new_tx_channel failed");
                }

                // RX channel on `in_pin`
                let mut rx_cfg: rmt_rx_channel_config_t = core::mem::zeroed();
                rx_cfg.gpio_num = in_pin as gpio_num_t;
                // Sourcing RX from REF_TICK (1 MHz) instead of APB (80 MHz)
                // lets the /256-max divider reach the low resolution we need.
                // At APB the floor is 312.5 kHz → ~104 ms signal_range_max_ns
                // cap, not enough margin over the slave's ~70 ms delay; with
                // REF_TICK the floor is 3.9 kHz → ~8 s cap.
                rx_cfg.clk_src = soc_periph_rmt_clk_src_t_RMT_CLK_SRC_REF_TICK;
                rx_cfg.resolution_hz = RX_RESOLUTION_HZ;
                rx_cfg.mem_block_symbols = 128;
                // The input comparator on the OT shield (custom PCB on this
                // device) inverts the bus signal — a LOW on the wire reads
                // HIGH on this GPIO and vice versa. The C++ OT library was
                // implicitly designed for that polarity; our Manchester
                // decoder expects the wire-side convention (start bit =
                // LOW → HIGH). Have RMT invert the input so the captured
                // symbols match.
                rx_cfg.flags.set_invert_in(1);

                let mut rx_chan: rmt_channel_handle_t = ptr::null_mut();
                if rmt_new_rx_channel(&rx_cfg, &mut rx_chan) != ESP_OK as esp_err_t {
                    rmt_del_channel(tx_chan);
                    return Err("rmt_new_rx_channel failed");
                }

                // Copy encoder — passes raw symbols through unchanged.
                let enc_cfg: rmt_copy_encoder_config_t = core::mem::zeroed();
                let mut encoder: rmt_encoder_handle_t = ptr::null_mut();
                if rmt_new_copy_encoder(&enc_cfg, &mut encoder) != ESP_OK as esp_err_t {
                    rmt_del_channel(tx_chan);
                    rmt_del_channel(rx_chan);
                    return Err("rmt_new_copy_encoder failed");
                }

                // Binary semaphore for RX done signalling.
                let sem = xQueueCreateCountingSemaphore(1, 0);
                if sem.is_null() {
                    rmt_del_encoder(encoder);
                    rmt_del_channel(tx_chan);
                    rmt_del_channel(rx_chan);
                    return Err("semaphore creation failed");
                }

                let ctx = Box::new(RxContext {
                    sem,
                    received_count: AtomicUsize::new(0),
                });

                // Register RX done callback. The user_ctx pointer must outlive
                // the channel — it points into the heap-allocated `ctx` Box.
                let cbs = rmt_rx_event_callbacks_t {
                    on_recv_done: Some(on_rx_done),
                };
                let ctx_ptr = ctx.as_ref() as *const RxContext as *mut core::ffi::c_void;
                if rmt_rx_register_event_callbacks(rx_chan, &cbs, ctx_ptr)
                    != ESP_OK as esp_err_t
                {
                    vQueueDelete(sem);
                    rmt_del_encoder(encoder);
                    rmt_del_channel(tx_chan);
                    rmt_del_channel(rx_chan);
                    return Err("rmt_rx_register_event_callbacks failed");
                }

                if rmt_enable(tx_chan) != ESP_OK as esp_err_t {
                    vQueueDelete(sem);
                    rmt_del_encoder(encoder);
                    rmt_del_channel(tx_chan);
                    rmt_del_channel(rx_chan);
                    return Err("rmt_enable(tx) failed");
                }
                if rmt_enable(rx_chan) != ESP_OK as esp_err_t {
                    rmt_disable(tx_chan);
                    vQueueDelete(sem);
                    rmt_del_encoder(encoder);
                    rmt_del_channel(tx_chan);
                    rmt_del_channel(rx_chan);
                    return Err("rmt_enable(rx) failed");
                }

                Ok(Self {
                    tx_chan,
                    rx_chan,
                    encoder,
                    rx_buffer: Box::new([rmt_symbol_word_t { val: 0 }; RX_BUFFER_SYMBOLS]),
                    ctx,
                    last_status: ResponseStatus::None,
                })
            }
        }

        pub fn send_request(&mut self, request: u32) -> u32 {
            let tx_symbols = encode_frame(request);

            unsafe {
                // Drain any stale semaphore signal left by a previous timed-out
                // receive whose callback may have fired after we'd already
                // given up waiting.
                let _ = xQueueReceive(self.ctx.sem, ptr::null_mut(), 0);

                // 1. Transmit the master frame first.
                //
                // Arming RX before TX would be tempting (no risk of missing a
                // leading edge), but on hardware where the master's IN pin
                // sees its own TX edges the RMT would capture the TX echo
                // and then close the receive window 1.5 ms later — well
                // before the slave's 20-100 ms response arrives. Transmitting
                // first sidesteps that, and the slave's spec-mandated
                // ≥ 20 ms turnaround leaves plenty of slack to arm RX.
                //
                // eot_level=1 holds the line HIGH after the stop bit.
                // OpenTherm idle = HIGH (no master current draw); leaving the
                // RMT default (eot=0, line LOW) keeps the bus in master-active
                // state for the entire inter-frame gap and the CWL never
                // responds.
                let mut tx_cfg: rmt_transmit_config_t = core::mem::zeroed();
                tx_cfg.loop_count = 0;
                tx_cfg.flags.set_eot_level(1);
                let tx_bytes = tx_symbols.len() * core::mem::size_of::<rmt_symbol_word_t>();
                if rmt_transmit(
                    self.tx_chan,
                    self.encoder,
                    tx_symbols.as_ptr() as *const core::ffi::c_void,
                    tx_bytes,
                    &tx_cfg,
                ) != ESP_OK as esp_err_t
                {
                    self.last_status = ResponseStatus::Invalid;
                    FreeRtos::delay_ms(RECOVERY_DELAY_MS);
                    return 0;
                }
                // Block until the wire-level TX is done (~34 ms).
                let _ = rmt_tx_wait_all_done(self.tx_chan, 200);

                // 2. Arm RX for the slave's response.
                //
                // signal_range_max_ns has to span both the leading HIGH idle
                // before the slave starts (20-800 ms per spec, ~70 ms on Wolf)
                // *and* the trailing idle after its stop bit that closes the
                // window. 1.5 ms would close the window before the slave even
                // begins, leaving `count = 0` and a spurious Invalid. 250 ms
                // covers worst-case observed response delays with margin,
                // while still letting the close-on-trailing-idle finish well
                // inside RESPONSE_TIMEOUT_MS.
                self.ctx.received_count.store(0, Ordering::Release);
                let rx_cfg = rmt_receive_config_t {
                    signal_range_min_ns: 1_000,
                    signal_range_max_ns: 250_000_000,
                };
                let rx_buf_ptr = self.rx_buffer.as_mut_ptr() as *mut core::ffi::c_void;
                let rx_buf_bytes = RX_BUFFER_SYMBOLS * core::mem::size_of::<rmt_symbol_word_t>();
                if rmt_receive(self.rx_chan, rx_buf_ptr, rx_buf_bytes, &rx_cfg)
                    != ESP_OK as esp_err_t
                {
                    // Reset channel state (RUN → ENABLE) so the next call
                    // can re-arm. Without this a single failure poisons the
                    // channel for the rest of the program's life.
                    self.reset_rx();
                    self.last_status = ResponseStatus::Invalid;
                    FreeRtos::delay_ms(RECOVERY_DELAY_MS);
                    return 0;
                }

                // 3. Wait for the RX-done ISR to give the semaphore.
                let took = xQueueReceive(
                    self.ctx.sem,
                    ptr::null_mut(),
                    ms_to_ticks(RESPONSE_TIMEOUT_MS),
                );
                if took != PD_TRUE {
                    // No edges ever arrived → signal_range_max_ns never
                    // triggered → channel still in RUN state. Reset so we
                    // can re-arm on the next poll.
                    self.reset_rx();
                    self.last_status = ResponseStatus::Timeout;
                    FreeRtos::delay_ms(RECOVERY_DELAY_MS);
                    return 0;
                }

                let count = self.ctx.received_count.load(Ordering::Acquire);
                let captured = &self.rx_buffer[..count.min(RX_BUFFER_SYMBOLS)];
                match decode_symbols(captured) {
                    Ok(frame) => {
                        self.last_status = ResponseStatus::Success;
                        FreeRtos::delay_ms(RECOVERY_DELAY_MS);
                        frame
                    }
                    Err(()) => {
                        self.last_status = ResponseStatus::Invalid;
                        FreeRtos::delay_ms(RECOVERY_DELAY_MS);
                        0
                    }
                }
            }
        }

        /// Force the RX channel back into the `ENABLE` state, aborting any
        /// in-flight receive. Used after a timeout when the ISR never fired
        /// to release the channel.
        unsafe fn reset_rx(&self) {
            let _ = rmt_disable(self.rx_chan);
            let _ = rmt_enable(self.rx_chan);
        }

        pub fn last_status(&self) -> ResponseStatus {
            self.last_status
        }

        pub fn build_request(msg_type: MessageType, data_id: u8, data: u16) -> u32 {
            build_frame(msg_type, data_id, data)
        }

        pub fn get_message_type(frame: u32) -> MessageType {
            extract_msg_type(frame)
        }
    }

    impl Drop for OpenTherm {
        fn drop(&mut self) {
            unsafe {
                rmt_disable(self.tx_chan);
                rmt_disable(self.rx_chan);
                rmt_del_encoder(self.encoder);
                rmt_del_channel(self.tx_chan);
                rmt_del_channel(self.rx_chan);
                vQueueDelete(self.ctx.sem);
            }
        }
    }
}

#[cfg(not(feature = "simulate-ot"))]
pub use rmt::OpenTherm;
